name: Lint, test and deploy preview client except main

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  lint-and-preview-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v2

      - name: Setup node env ğŸ—
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          registry-url: 'https://registry.npmjs.org'
          # now can cache https://github.com/actions/setup-node/releases/tag/v2.4.0
          cache: yarn

      - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        run: yarn

      - name: Run functions linter ğŸ‘€
        run: yarn api:lint

      - name: Run client linter ğŸ‘€
        if: success()
        run: yarn next:lint

      - name: Run client tests ğŸ§ª
        run: yarn next:test

      - name: Deploy to Vercel (Preview) ğŸŒŸ
        uses: amondnet/vercel-action@v20
        with:
          # This will be preview deployment because --prod is not set
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG }} #Required
          vercel-project-id: 'seekfiction' #Required
