name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Setup node env ğŸ—
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          registry-url: 'https://registry.npmjs.org'
          # now can cache https://github.com/actions/setup-node/releases/tag/v2.4.0
          cache: yarn

      - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        run: yarn

      - name: Check if functions code changed ğŸ‘€
        uses: technote-space/get-diff-action@v5
        id: functions-diff
        with:
          PATTERNS: |
            packages/api/*

      # Somehow we still need to set function config via GitHub secret
      # Detail: https://github.com/w9jds/firebase-action/issues/86
      - name: Set configs for Firebase âœ… (useand FIREBASE_FUNCTIONS_ENV_VARIABLES)
        if: steps.functions-diff.outputs.diff
        uses: w9jds/firebase-action@master
        with:
          args: functions:config:set ${{ secrets.FIREBASE_FUNCTIONS_ENV_VARIABLES }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # Functions lint will run with predeploy script in firebase.json
      # so we don't have to run lint before this
      - name: Deploy functions to Firebase ğŸ”¥ (use FIREBASE_TOKEN)
        if: steps.functions-diff.outputs.diff
        uses: w9jds/firebase-action@master
        with:
          # --force to delete functions
          args: deploy --only functions --force --debug
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # solve problem after diff
      - name: Reset diff remote ğŸ˜
        run: git remote remove get-diff-action

      - name: Check if client code changed ğŸ‘€
        uses: technote-space/get-diff-action@v5
        id: client-diff
        with:
          PATTERNS: |
            packages/web-next/*

      - name: Run client linter ğŸ‘€
        if: steps.client-diff.outputs.diff
        run: yarn next:lint

      - name: Run client tests ğŸ§ª
        if: steps.client-diff.outputs.diff
        run: yarn next:test

      - name: Deploy to Vercel (Production) ğŸš€
        if: steps.client-diff.outputs.diff
        uses: amondnet/vercel-action@v20
        with:
          # This will be production deployment because --prod is set
          vercel-args: '--prod'
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG }} #Required
          vercel-project-id: 'seekfiction' #Required
