name: Deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v2

      - name: Setup node env ğŸ—
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          registry-url: 'https://registry.npmjs.org'
          # now can cache https://github.com/actions/setup-node/releases/tag/v2.4.0
          cache: yarn

      - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        run: yarn

      - name: Build package ğŸ
        run: yarn workspace @sasigume/seekfiction-commons build

      - name: Publish package ğŸš€
        run: npm publish packages/seekfiction-commons --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

  deploy:
    if: always()
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Setup node env ğŸ—
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          registry-url: 'https://registry.npmjs.org'
          # now can cache https://github.com/actions/setup-node/releases/tag/v2.4.0
          cache: yarn

      - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        run: yarn

      # Somehow we still need to set function config via GitHub secret
      # Detail: https://github.com/w9jds/firebase-action/issues/86
      - name: Set configs for Firebase âœ… (useand FIREBASE_FUNCTIONS_ENV_VARIABLES)
        uses: w9jds/firebase-action@master
        with:
          args: functions:config:set ${{ secrets.FIREBASE_FUNCTIONS_ENV_VARIABLES }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # Functions lint will run with predeploy script in firebase.json
      # so we don't have to run lint before this
      - name: Deploy functions to Firebase ğŸ”¥ (use FIREBASE_TOKEN)
        if: success()
        uses: w9jds/firebase-action@master
        with:
          # --force to delete functions
          args: deploy --only functions --force --debug
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Run client linter ğŸ‘€
        if: success()
        run: yarn next:lint

      - name: Run client tests ğŸ§ª
        run: yarn next:test

      - name: Deploy to Vercel (Production) ğŸš€
        # We won't deploy client unless functions are successfully deployed
        if: success()
        uses: amondnet/vercel-action@v20
        with:
          # This will be production deployment because --prod is set
          vercel-args: '--prod'
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG }} #Required
          vercel-project-id: 'seekfiction' #Required
